# Generated by Django 4.1.2 on 2023-01-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_profile_delete_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
